### ISSUE TITLE
mkdir(): Permission denied?

### ISSUE THREAD

**Issue by venkatiiitb** [anakadote/ImageManager#2]
In my localhost i was not getting this error but in aws server even though i gave 777 permissions to my public/uploads folder. It's giving error.

**Comment by anakadote** [comment]
What is the error?

**Comment by venkatiiitb** [comment]
i was getting error saying mkdir() permission denied. Then i solved it by assigning my ubuntu user to www-data (apache group). Later i got another error chmod() permission denied that also solved. after than i am getting every image not found even though i had images in the folder which you package created.

**Comment by anakadote** [comment]
Make sure that you are including the fully qualified file name (absolute path and file name) to the image in your getImagePath() call.

**Comment by venkatiiitb** [comment]
I was able to see the image in my local server with the same code but in server it gives your image not found error image.

**Comment by anakadote** [comment]
That means the image path you're using is incorrect. Try something like 
ImageManager::getImagePath( public_path() . '/assets/img/' . $filename, 100, 100, 'fit')
