### ISSUE TITLE
Delete image doesn't work.

### ISSUE THREAD

**Issue by santoshachari** [anakadote/ImageManager#3]
Hi There,

I've tried this a few times, but the re-sized images continue to exist in cached folders. 

ImageManager::deleteImage( public_path() . '/img/' . $image->filename );

**Comment by anakadote** [comment]
Can you please post the relevant code from your project?

**Comment by santoshachari** [comment]
I did try with usual project. Except delete function, everything else worked. I can try replicated the code: in Laravel 4.2.

**Comment by anakadote** [comment]
I mean can you show me your code.

**Comment by santoshachari** [comment]
This the snippet for deleting images from product gallery. 

`$product_images = ProductImages::find($image_entry_id);
//dd(public_path() . '/uploads/products/' . $product_images->image );
ImageManager::deleteImage( public_path() . "\\uploads\\products\\" . $product_images->image);   
$product_images -> delete();``

**Comment by anakadote** [comment]
Are you on Windows? (You're using back slashes but front slashes in the line of code above).

What happens when you try this?:

```
if( file_exists( public_path() . "\uploads\products\" . $product_images->image ) ){
   ImageManager::deleteImage( public_path() . "\uploads\products\" . $product_images->image);
} else {
   die('The image does not exist.');
}
```

**Comment by santoshachari** [comment]
Yes I am using this on Windows Server. Will try this. Thanks. Give me 30 mins to get back. :)

**Comment by santoshachari** [comment]
I have just tried it again.

Tried image.jpg,  which was resized, and added to 125x125 and 600x600 folders. 

When I use deleteImage(), however, images are still in these folders.

**Comment by santoshachari** [comment]
Just tried with a fresh laravel 4.2 Install. 
Same issue - the image is deleted, but it's re sized versions are not.

**Comment by anakadote** [comment]
@santoshachari This bug has been fixed in the latest version of the package. Thanks!

**Comment by santoshachari** [comment]
Thanks @anakadote . :+1: 

And for working this plugin out in the first place.
